baseurl      = "http://foxmaccloud.com/"
title        = "FoxCorp"
languageCode = "en-us"
theme        = "hello-friend-ng"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.




[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "A Smooth Sea Never Made a Skilled Sailor"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "FoxCorp, frontier frontline of Hacking!"
  keywords = "homepage, home"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "FoxCorp"
    subtitle = "Welcome to FoxCorp!"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # Social icons
    [[params.social]]
      name = "twitter"
      url  = "https://twitter.com/FoxMacSwagger"

    [[params.social]]
      name = "codepen"
      url  = "https://www.hackthebox.eu/profile/38606"

    [[params.social]]
      name = "github"
      url  = "https://github.com/FoxMaccloud/"

    [[params.social]]
      name = ""
      url  = "https://discord.gg/VHUKpca"


[permalinks]
      posts = "/posts/:year/:month/:title/"




[menu]
  # And you can even create generic menu
  [[menu.main]]
    identifier = "whoami"
    name       = "Whoami?"
    url        = "whoami/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "writeups"
    name       = "Writeups"
    url        = "writeups/"
